name: Cypress Tests

on:
  push:
    branches: [main]

jobs:
  cypress-run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2.4.2
        
      #setup node 
      - name: Setup Node.js environment
        uses: actions/setup-node@v3.1.1
        
      - name: Cypress run
        uses: cypress-io/github-action@v2.9.7
        with:
          install: false
          start: npm --version