name : Cypress file test
on: [push]
jobs: 
    cypress-run:
      runs-on: ubuntu-latest
      steps:
      - name: Checkout
        uses: actions/checkout@v2.4.2

      - name: cypress.io
        uses: cypress-io/github-action@v2.9.7
          with: 
            start: npm start
